---
title: "p8105_hw3_hz2771"
author: 'Haolin Zhong (UNI: hz2771)'
date: "2021/10/12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(p8105.datasets)
library(patchwork)
```


# Problem 1

## Load data

```{r}
data("instacart")
```

## Count aisles

```{r}
instacart %>% 
  summarize(n_aisles = n_distinct(aisle_id))
```

## most ordered aisles
```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarize(sold = n()) %>% 
  filter(sold == max(sold)) %>% 
  select(aisle)
```

## Visualizing aisles sold

```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarize(n_sold = n()) %>% 
  filter(n_sold > 10000) %>% 
  ggplot(aes(x = reorder(aisle, -n_sold), y = n_sold)) +
  geom_col() + 
  scale_x_discrete(limits = ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  xlab("aisle") +
  ylab("ordered times")

```

## most popular in 3

```{r}
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  count(aisle, product_name, name = "n_item_sold") %>% 
  group_by(aisle) %>% 
  mutate(inner_rank = min_rank(desc(n_item_sold))) %>% 
  filter(inner_rank < 4) %>% 
  arrange(aisle, inner_rank) %>% 
  select(-inner_rank, most_popular_items = product_name)
```

## apples and ice cream

```{r, message=FALSE, warning=FALSE}
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(mean_hour_ordered = round(mean(order_hour_of_day),2)) %>% 
  mutate(order_dow = recode(order_dow,
                            `0` = "Sun",
                            `1` = "Mon",
                            `2` = "Tue",
                            `3` = "Wed",
                            `4` = "Thr",
                            `5` = "Fri",
                            `6` = "Sat")
         ) %>% 
  pivot_wider(names_from = order_dow, values_from = mean_hour_ordered)
```


# Problem 2

## Load data

```{r}
data("brfss_smart2010")
```

## Data cleaning

```{r}
brfss_df = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = 
           factor(response, 
                  levels = c("Poor", "Fair", "Good", "Very good", "Excellent")))
```

## state observations

### 2002

```{r}
brfss_df %>% 
  filter(year == 2002) %>% 
  group_by(locationabbr, locationdesc) %>% 
  summarize() %>% 
  count(locationabbr, name = "n_obs") %>% 
  filter(n_obs >= 7) %>% 
  select(locationabbr)
```

### 2010

```{r}
brfss_df %>% 
  filter(year == 2010) %>% 
  group_by(locationabbr, locationdesc) %>% 
  summarize() %>% 
  count(locationabbr, name = "n_obs") %>% 
  filter(n_obs >= 7) %>% 
  select(locationabbr)
```

## spaghetti plot

```{r}
brfss_df %>% 
  filter(response == "Excellent") %>% 
  group_by(year, locationabbr) %>% 
  summarize(mean_val = mean(data_value)) %>% 
  ggplot(aes(x = year, y = mean_val, group = locationabbr, color = locationabbr)) +
  geom_line() +
  theme(legend.position = "right")


```

## two panel plot

```{r, warning=FALSE}
brfss_df %>% 
  filter(locationabbr == "NY") %>%
  filter(year %in% c(2006, 2010)) %>% 
  ggplot(aes(x = response, y = data_value, fill = response)) +
  geom_violin(adjust = .6, width = 1.5) +
  geom_boxplot(width = .05, fill = "black", outlier.colour = NA) +
  stat_summary(fun.y = median, geom = "point", fill = "white", shape = 21, size = 2.5) +
  facet_grid(~year)
```

# Problem 3

```{r}
aclrm_data_path = "./data/accel_data.csv"
aclrm_df = read_csv(aclrm_data_path) %>% 
  janitor::clean_names() %>% 
  pivot_longer("activity_1":"activity_1440", 
               names_to = "minute", 
               values_to = "act_count", 
               names_prefix = "activity_") %>% 
  mutate(minute = as.integer(minute),
         is_weekend = ifelse(day %in% c("Saturday", "Sunday"), 1, 0))

```


```{r}
aclrm_df %>% 
  group_by(day, week) %>% 
  summarize(daily_act_count = sum(act_count)) %>% 
  pivot_wider(names_from = day, values_from = daily_act_count)
```


```{r}
aclrm_df %>% 
  ggplot(aes(x = minute, y = act_count, color = day, group = day_id)) +
  geom_line(alpha = 0.2)
```



```{r}
aclrm_df %>% 
  mutate(week = recode(week,
                       `1` = "week 1",
                       `2` = "week 2",
                       `3` = "week 3",
                       `4` = "week 4",
                       `5` = "week 5")) %>% 
  ggplot(aes(x = minute, y = act_count)) +
  geom_line(alpha = 0.8) +
  geom_smooth(color = "lightblue") +
  facet_grid(week ~ day, scales = "free")
```













